### ISSUE TITLE
Codestar Framework Free Issue 

### ISSUE THREAD

**Issue by nuralamsiddikashik** [Codestar/codestar-framework-old#626]
Hello , 
I have used the Codester framework for a long time. But I'm surprised to see the Codester premium version. The at least free Codester meta box and theme options, hope to be great for everyone.

Thanks 
Nur Alam Siddik Ashik

**Comment by Codestar** [comment]
Free version offers only **Admin Options**. Metabox Options, Customize Options, Taxonomy Options, Shortcode Generator included in premium version. If you was used to v1.0, no worries. I will provide a download link for old version.

I want to speed up to this project in 2019, You can think "Premium version" is a kind of make a donate for this project.

Regards, Codestar

**Comment by raajen** [comment]
@Codestar 
Currently repo doesn't shows anything except the coming soon.

Please can you update the repo with both version 1.0 and version 2.0 releases?

Regards,
Rajendra

**Comment by Codestar** [comment]
@raajen Ok, i switched this repo as **codestar-framework-old**, i will continue to new version on **codestar-framework** repo. right?

Regards, Codestar

**Comment by raajen** [comment]
Also please update the new codestar framework as well :)

Regards,
Rajendra

**Comment by raajen** [comment]
Also Can I test the new pro version of your framework?? We've been
contributing helping in fixing issues also I was in your pro version group
to further improve your pro version of codestar framework. It is upto you
but it would be grateful if you would like to share your pro version just
for testing purpose.

Regards
Rajendra

**Comment by Codestar** [comment]
@raajen Yes of course, it will be on https://github.com/Codestar/codestar-framework within 1-2 days

**Comment by k4mrul** [comment]
I assume 1-2 days already passed

**Comment by raajen** [comment]
@k4mrul He is waiting for his pro framework to be approved in 'Codecanyon' so that he could release free version in github. 

@Codestar What is the progress of your pro framework mate? Anyway best of luck.

It would be great you could release the free version here in github so that your users don't have to wait much 👍

**Comment by ashawkat** [comment]
@nuralamsiddikashik I think you're right. I've been using cs for a long time now & it's pretty sad that this premium version will kill usage of this good framework. @Codestar 
I think you should keep the metabox & admin option free of cost so that you can get many people using your framework. Otherwise there are cmb2 type metabox framework or redux type admin framework which has good support & usage also. Keep that in mind also. 
Please try to keep the metabox at least for free.

**Comment by Codestar** [comment]
@k4mrul Yes right : ( Still waiting on the CodeCanyon review queue.

@raajen thanks for explain. I need to wait unilt review progress done for avoid license issues. you know Evnato rules is strict.

@ashawkat Old version still in the live. You can continue to v1. Sorry but metabox option will be premium. Also Redux metabox extension is premium. One-time payment is not will be kill to usage of this framework. i think i deserve that :smile: Ok let's see what happened.

**Comment by Codestar** [comment]
V2 Released: https://github.com/Codestar/codestar-framework
